module.exports = [
  "Baluwarti",
  "Banyuanyar",
  "Bumi",
  "Danukusuman",
  "Gajahan",
  "Gandekan",
  "Gilingan",
  "Jagalan",
  "Jajar",
  "Jayengan",
  "Jebres",
  "Joyosuran",
  "Joyotakan",
  "Kadipiro",
  "Kampung Baru",
  "Karangasem",
  "Kauman",
  "Kedung Lumbu",
  "Kemlayan",
  "Kepatihan Kulon",
  "Kepatihan Wetan",
  "Keprabon",
  "Kerten",
  "Kestalan",
  "Ketelan",
  "Kratonan",
  "Laweyan",
  "Manahan",
  "Mangkubumen",
  "Mojosongo",
  "Nusukan",
  "Pajang",
  "Pasar Kliwon",
  "Panularan",
  "Penumping",
  "Pucang Sawit",
  "Punggawan",
  "Purwodiningratan",
  "Purwosari",
  "Sangkrah",
  "Semanggi",
  "Serengan",
  "Setabelan",
  "Sewu",
  "Sondakan",
  "Sriwedari",
  "Sudiroprajan",
  "Sumber",
  "Tegalharjo",
  "Timuran",
  "Tipes"
]